services:
  postgres:
    image: postgres:17
    container_name: marquei-api
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
